language: python
cache: pip
python: 3.7
install: pip install flake8 -r requirements.txt
before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script: chmod +x build.sh && ./build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x deploy.sh && ./deploy.sh
  on:
    branch: master
